M48
; DRILL file {KiCad 9.0.2} date 2025-06-11T23:47:43-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-11T23:47:43-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X135.0Y-127.4
T2
X168.4Y-146.0
M30
